name: wf-ci
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
  push:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome steps
        run: echo "Welcome to CI Pipeline"
      - name: Checkout Repo
        uses: actions/checkout@v4  
      - name: Lint HTML Files
        run: npx htmlhint "**/*.html"
      - name: Lint CSS Files 
        run: npx stylelint "**/*.css"
      - name: Build Website With Parcel
        run: npx parcel build src/index.html --dist-dir dist  